### ISSUE TITLE
Failed to convert the nuScenes dataset into KITTI format

### ISSUE THREAD

**Issue by litian1045** [YurongYou/MODEST#1]
Hi, I am using the data_processing/nuscenes/nusc2kitti_boston.py script to convert nuScenes data into KITTI format, but got errors with the information as below:

 Traceback (most recent call last):
  File "nusc2kitti_boston.py", line 585, in <module>
    kc.nuscenes_gt_to_kitti()
  File "nusc2kitti_boston.py", line 226, in nuscenes_gt_to_kitti
    for idx, (lidar_token, cam_front_token) in tqdm(list(enumerate(sample_tokens))))
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "nusc2kitti_boston.py", line 343, in process_token_to_kitti
    for sample_annotation_token in sample_annotation_tokens:
NameError: name 'sample_annotation_tokens' is not defined

I have checked this script and it seems because of a lack of definition of the 'sample_annotation_tokens'. 
Could you please have a look at this? 
Many thanks.

**Comment by YurongYou** [comment]
Thanks for your interst! I fixed it in the new commit, please pull it and see if it works.
